// File generated by FlutterFire CLI & Livora System Engine.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT37porW9iF07VNJnoR6oqqdV15w2jusM',
    appId: '1:704226223285:android:e09f5a64485e35ad890afc',
    messagingSenderId: '704226223285',
    projectId: 'livora-app-fd5a3',
    storageBucket: 'livora-app-fd5a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9iTecFXGY3SETm98ngOXIjBWWNGVfTE',
    appId: '1:704226223285:ios:96bd02ac9ddc473a890afc',
    messagingSenderId: '704226223285',
    projectId: 'livora-app-fd5a3',
    storageBucket: 'livora-app-fd5a3.firebasestorage.app',
    iosBundleId: 'com.livoralabs.livoraLabs',
  );
}
